### ISSUE TITLE
Korean letter encoding error on Windows

### ISSUE THREAD

**Issue by jeonghyunwoo** [r-dbi/RSQLite#233]
Hi, I'm beginner to RSQLite and have a ciritical problem on encoding.
Belows are an example of the problem which I'm suffering.

conn = dbConnect(SQLite(), ':memory')
a = data.frame(가나다 = 1)
dbWriteTable(conn, 'a', a)
dbReadTable(conn, 'a')
      **Error in make.names(names(out), unique = TRUE) :  invalid multibyte string 1**

**Comment by krlmlr** [comment]
Thanks. This works for me on Linux. What OS are you using?

**Comment by jeonghyunwoo** [comment]
My pc is on windows7.
Thanks : )

2017. 12. 10. 오전 6:23에 "Kirill Müller" <notifications@github.com>님이 작성:

**Comment by wush978** [comment]
Dear @krlmlr 

I have the same bug in my course of teaching RSQLite and all of my students who use windows 7 or windows 10 have the same bug, too.
Note that previous version of RSQLite on R 3.4 did not have this issue on Windows.

Moreover, if I try to bypass this issue via adding `check.names = FALSE` in `dbReadTable`. However, if I try to append the same table via `dbWriteTable(..., append = TRUE)`, another encoding issue related to `dbListField` occurs.

Since this bug is essential in my class, which is focus on using R to process Open Data in Taiwan, I am willing to send a PR to fix it if you agree.

Best,
Wush

**Comment by wush978** [comment]
I write a unit test [`test-encoding.R`](https://github.com/wush978/RSQLite/commit/5c290eefcbc9f5e7d376248cbd2a24db22df978b) as a start and the [log of appveyor](https://ci.appveyor.com/project/wush978/rsqlite/builds/20694175) does show that it fails on windows.

**Comment by wush978** [comment]
Under the latest RSQLite, both the content of the data.frame and column name will be converted to UTF-8 after `dbWriteTable` under correct system locale (`cht` on windows and `zh_TW.UTF-8` on others).
The bug is due to the `dbReadTable` and `dbListFields` cannot correctly process the UTF-8 encoded string.
We need to mark the string via `Encoding<-` manually.
After letting them correctly process the UTF-8 strings and setting the system locale, the tests are passed.
Here is the details: https://github.com/r-dbi/RSQLite/compare/master...wush978:master
Should I send a PR or will you correct it by yourself?

Note that the BIG5 encoding is the default encoding for tradition Chinese on windows. 
So I ask the testthat to skip the test on non-windows platform.
Otherwise, issues similar to https://github.com/tidyverse/tibble/issues/87#issuecomment-433630499 will occur.

**Comment by shrektan** [comment]
Just share a tip that you can install the binary version by running `install.packages('https://ci.appveyor.com/api/buildjobs/xfqrv3e8ao383dkh/artifacts/RSQLite_2.1.1.9002.zip', type = 'binary', repos = NULL)` (assume windows and R version >= 3.5.0)


And the following example works for me.

```
con <- DBI::dbConnect(RSQLite::SQLite())
tbl <- data.frame("中文" = 'a')
DBI::dbWriteTable(con, name = 'test', value = tbl)
got <- DBI::dbListFields(con, 'test')
got
Encoding(got)
DBI::dbWriteTable(con, name = 'test', value = tbl, append = TRUE)
DBI::dbReadTable(con, 'test')
```

**Comment by wush978** [comment]
Thank you.

I'll use the appveyor to test your code based on the works in https://github.com/r-dbi/RSQLite/issues/233#issuecomment-443402260 .

**Comment by wush978** [comment]
The [test](https://ci.appveyor.com/project/wush978/rsqlite/builds/21293953) is failed:

```
== testthat results  ===========================================================
  OK: 536 SKIPPED: 5 FAILED: 2
  1. Error: write a table whose colnames is BIG5 encoded (@test-encoding.R#17) 
  2. Error: write a table whose colnames is UTF-8 encoded (@test-encoding.R#33) 
``` 

Compared with the [previous results](https://ci.appveyor.com/project/wush978/rsqlite/builds/21293948), the encoding issue related to `dbListFields` is fixed, but `dbReadTable` is not.

**Comment by wush978** [comment]
Sorry, the failures in https://github.com/r-dbi/RSQLite/issues/233#issuecomment-450561678 might not be relevant. I am checking my script.

**Comment by shrektan** [comment]
I believe it fails due to your raw char cannot be represented on the Appveyor machine.

It's quite complicated and hard to explain the reason clearly. However, the rule of thumb is:

1. If you want to test UTF-8, please use `cat(stringi::stri_escape_unicode('中文字符'))` and write the non-ASCII strings in the format like `\uxxxx`

1. If you insist to test non-ASCII strings under native encoding, please use the latin1 strings (the only way that can be ensured to run under any OS), see the test example in data.table like [this](https://github.com/Rdatatable/data.table/pull/2715/files)

**Comment by wush978** [comment]
Thank you for your works, I manually confirm that the original issue is no longer existed.

And thanks for your comments about the encoding. I learned a lot from your blogs.

**Comment by krlmlr** [comment]
@wush978: Would you like to submit your tests as a PR?

**Comment by wush978** [comment]
@krlmlr I am glad to. The PR will be sent after the errors indicated by @shrektan are fixed.

**Comment by krlmlr** [comment]
Can we close this now?
