### ISSUE TITLE
Coerce POSIXct to julian date when writing

### ISSUE THREAD

**Issue by hadley** [r-dbi/RSQLite#237]
``` r
library(DBI)

df <- data.frame(date = ISOdate(2016, 1, 1:5))
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "df", df)

# Date time functions don't work
dbGetQuery(con, "SELECT date, date(date) FROM df")
#>         date date(date)
#> 1 1451649600         NA
#> 2 1451736000         NA
#> 3 1451822400         NA
#> 4 1451908800         NA
#> 5 1451995200         NA

# But they do if we convert to Julian data time
offset <- dbGetQuery(con, "SELECT julianday('1970-01-01 12:00')")[[1]]

df2 <- data.frame(date = as.numeric(julian(df$date) + offset - 1))
dbWriteTable(con, "df2", df2, overwrite = TRUE)
dbGetQuery(con, "SELECT date, date(date), time(date) FROM df2")
#>      date date(date) time(date)
#> 1 2457388 2016-01-01   00:00:00
#> 2 2457390 2016-01-02   00:00:00
#> 3 2457390 2016-01-03   00:00:00
#> 4 2457392 2016-01-04   00:00:00
#> 5 2457392 2016-01-05   00:00:00
```

**Comment by ggrothendieck** [comment]
This would have several undesirable implications:

  1. not backward compatible
  2. performance hit due to conversions back and forth when uploading and downloading even if you are not using the datetime fields.
  3. I don't think we should be imposing representations onto SQLite that don't exist. RSQLite should be a thin layer. The fact is that there are no datetime or date types in SQLite. Just because some functions in SQLite make certain assumptions does not change this.

If RSQLite wants to make this easier it could add some SQL functions that specifically assume the internal representation of datetimes and dates used in R.  This would have no impact on existing code and no adverse performance impact.  

Beyond adding some SQL functions it should be up to SQLite to address this, not RSQLite.

**Comment by krlmlr** [comment]
Thanks. I'm especially worried about backward compatibility, but the existence of `date()` in SQLite does justify using this storage format for the default conversion. Perhaps we could make this configurable via pkgconfig?

**Comment by ggrothendieck** [comment]
RSQLite 2.0 breaks RSQLite backward compatibility in a fundamental way that would be difficult to fix at a higher level so I suggest you fork RSQLite and make the pre-2.0 version  available on CRAN as RSQLite and verson 2.0 onwards available as RSQLite2 and maintain both like ggplot2 did.  Then you can add all the breaking changes you like without affecting a large number of users who just want it to work.

**Comment by krlmlr** [comment]
We could provide sqlite builtin functions that works like `date()` and `time()` but assumes R `POSIXct` values. How about `r_date()` and `r_time()`? This will simplify the roundtrip without affecting compatibility.

**Comment by ggrothendieck** [comment]
If your suggestion is just to provide some additional SQL functions that users can use or not and otherwise everything works the same as it does now so that existing code continues to work then that would be ok.  In particular there should be no automatic conversions upon upload or download that do not exist now.    If you want to create additional packages that add semantic layers on top of RSQLite that is fine as long as RSQLite itself continues to be a thin layer that is compatible with past versions.

**Comment by krlmlr** [comment]
Let's continue discussing the implementation in #333.
